# Generated by Django 6.0.3 on 2026-04-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
