# Generated by Django 6.0.3 on 2026-04-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0002_perfildocente_bio_perfilempresa_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='grado',
            field=models.CharField(choices=[('4to_medio', '4to_medio'), ('egresado', 'Egresado')], default='4to_medio', max_length=15),
        ),
    ]
