# Generated by Django 6.0.3 on 2026-04-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0003_alter_perfilestudiante_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_estudiante', models.TextField(blank=True, null=True)),
                ('mensaje_empresa', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Contratado', 'estado_contratado'), ('Negado', 'estado_negado'), ('Pendiente', 'estado_pendiente')], default='Pendiente', max_length=15)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.perfilestudiante')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.ofertalaboral')),
            ],
        ),
    ]
