# Generated by Django 6.0.3 on 2026-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0004_postulacion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'oferta'), name='estudiante_oferta'),
        ),
    ]
