# Generated by Django 6.0.3 on 2026-04-04 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0005_postulacion_estudiante_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionesFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('post', 'Post'), ('empleo', 'Empleo'), ('evento', 'Evento')], default='post', max_length=6)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
