# Generated by Django 6.0.3 on 2026-04-04 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0006_publicacionesfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='usuario_reportado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
