# Generated by Django 6.0.3 on 2026-04-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0007_reporte_usuario_reportado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(choices=[('part_time', 'Part_Time'), ('full_time', 'Full_Time'), ('fines_de_semana', 'Fines_de_Semana'), ('practicas', 'Practicas')], default='part_time', max_length=16)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.perfilestudiante')),
            ],
        ),
    ]
