# Generated by Django 6.0.3 on 2026-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0008_disponibilidad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disponibilidad',
            constraint=models.UniqueConstraint(fields=('disponibilidad', 'estudiante'), name='disponibilidad_estudiante'),
        ),
    ]
