# Generated by Django 6.0.3 on 2026-04-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0009_disponibilidad_disponibilidad_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='disponibilidad_requerida',
            field=models.CharField(blank=True, choices=[('part_time', 'Part_Time'), ('full_time', 'Full_Time'), ('fines_de_semana', 'Fines_de_Semana'), ('practicas', 'Practicas')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='grado_requerido',
            field=models.CharField(blank=True, choices=[('4to_medio', '4to_medio'), ('egresado', 'Egresado')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='HabilidadRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=20)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.ofertalaboral')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('habilidad', 'oferta'), name='habilidad_oferta')],
            },
        ),
    ]
