# Generated by Django 6.0.3 on 2026-04-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0010_ofertalaboral_disponibilidad_requerida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadrequerida',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_requeridas', to='red_talento.ofertalaboral'),
        ),
    ]
