# Generated by Django 6.0.3 on 2026-04-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0011_alter_habilidadrequerida_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='red_talento.perfilestudiante'),
        ),
    ]
