# Generated by Django 6.0.3 on 2026-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0012_alter_disponibilidad_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='modalidad',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('semi_presencial', 'Semi-Presencial')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='remuneracion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
