# Generated by Django 6.0.3 on 2026-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0013_ofertalaboral_modalidad_ofertalaboral_remuneracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('Contratado', 'estado_contratado'), ('Negado', 'estado_negado'), ('Rechazado', 'estado_rechazado'), ('Seleccionado', 'estado_seleccionado'), ('Pendiente', 'estado_pendiente')], default='Pendiente', max_length=15),
        ),
    ]
