# Generated by Django 6.0.3 on 2026-04-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0013_ofertalaboral_modalidad_ofertalaboral_remuneracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=100)),
                ('criterio_codigo', models.CharField(blank=True, choices=[('habilidad_aprobada', 'Habilidad_aprobada'), ('empleo_conseguido', 'Empleo_conseguido'), ('3_cursos_completados', '3_Cursos_Completados'), ('5_cursos_completados', '5_Cursos_Completados'), ('10_cursos_completados', '10_Cursos_Completados'), ('perfil_completo', 'Perfil_Completo')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsigniaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.perfilestudiante')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_talento.insignias')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'insignia'), name='estudiante_insignia')],
            },
        ),
    ]
