# Generated by Django 6.0.3 on 2026-04-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0014_alter_postulacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='disponibilidad',
            field=models.CharField(choices=[('part_time', 'Part-time'), ('full_time', 'Full-time'), ('practica', 'Práctica'), ('no_disponible', 'No disponible')], default='part_time', max_length=16),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='disponibilidad_requerida',
            field=models.CharField(blank=True, choices=[('part_time', 'Part-time'), ('full_time', 'Full-time'), ('practica', 'Práctica'), ('no_disponible', 'No disponible')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='grado',
            field=models.CharField(choices=[('1ro_medio', '1ro_medio'), ('2do_medio', '2do_medio'), ('3ro_medio', '3ro_medio'), ('4to_medio', '4to_medio'), ('egresado', 'Egresado')], default='4to_medio', max_length=15),
        ),
    ]
