# Generated by Django 6.0.3 on 2026-04-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0014_insignias_insigniaestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('plataforma', models.CharField(choices=[('youtube', 'YouTube'), ('udemy', 'Udemy'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('especialidad', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=12)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='red_talento.perfildocente')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='red_talento.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_completados', to='red_talento.perfilestudiante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'curso'), name='estudiante_curso')],
            },
        ),
    ]
