# Generated by Django 6.0.3 on 2026-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0015_alter_disponibilidad_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionesfeed',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
