# Generated by Django 6.0.3 on 2026-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0015_perfildocente_es_admin_curso_cursocompletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidades',
            name='tipo',
            field=models.CharField(choices=[('tecnica', 'Técnica'), ('blanda', 'Blanda')], default='tecnica', max_length=10),
        ),
    ]
