# Generated by Django 6.0.3 on 2026-04-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0016_habilidades_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='video_pitch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
