# Generated by Django 6.0.3 on 2026-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0017_perfilestudiante_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
