# Generated by Django 6.0.3 on 2026-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0018_perfildocente_foto_perfil_perfilempresa_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionesfeed',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='feed_imagenes/'),
        ),
    ]
