# Generated by Django 6.0.3 on 2026-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0019_publicacionfeed_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
