# Generated by Django 6.0.3 on 2026-04-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0020_usuario_suspendido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='red_talento.publicacionesfeed'),
        ),
    ]
