# Generated by Django 6.0.3 on 2026-04-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0021_reporte_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='horario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='que_buscamos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
