# Generated by Django 6.0.3 on 2026-08-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_talento', '0022_perfilempresa_descripcion_perfilempresa_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='publicacion_mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
